//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TOSS_UPGRADE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BankAccountTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BankAccountTable()
        {
            this.Barangay_BarangayBankAccount = new HashSet<Barangay_BarangayBankAccount>();
            this.CheckInventoryTables = new HashSet<CheckInventoryTable>();
        }
    
        public int BankAccountID { get; set; }
        public int BankID { get; set; }
        public string AccountName { get; set; }
        public string AccountNo { get; set; }
        public int SubFundID { get; set; }
        public int GeneralAccountID { get; set; }
        public int AccountTypeID { get; set; }
    
        public virtual BankAccount_AccountType BankAccount_AccountType { get; set; }
        public virtual BankAccountTable BankAccountTable1 { get; set; }
        public virtual BankAccountTable BankAccountTable2 { get; set; }
        public virtual BankTable BankTable { get; set; }
        public virtual GeneralAccount GeneralAccount { get; set; }
        public virtual SubFund SubFund { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Barangay_BarangayBankAccount> Barangay_BarangayBankAccount { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CheckInventoryTable> CheckInventoryTables { get; set; }
    }
}
