//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TOSS_UPGRADE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payee
    {
        public int PayeeID { get; set; }
        public string PayeeName { get; set; }
        public string PayeeAddress { get; set; }
        public Nullable<int> DepartmentID { get; set; }
    
        public virtual Signatory_DepartmentTable Signatory_DepartmentTable { get; set; }
    }
}
