//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TOSS_UPGRADE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Section
    {
        public int SectionID { get; set; }
        public string SectionName { get; set; }
        public int DepartmentID { get; set; }
        public int FunctionID { get; set; }
    
        public virtual Function Function { get; set; }
        public virtual Signatory_DepartmentTable Signatory_DepartmentTable { get; set; }
    }
}
