//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TOSS_UPGRADE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubMajorAccountGroup
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SubMajorAccountGroup()
        {
            this.GeneralAccounts = new HashSet<GeneralAccount>();
        }
    
        public int SubMajorAccountGroupID { get; set; }
        public string SubMajorAccountGroupName { get; set; }
        public string SubMajorAccountGroupCode { get; set; }
        public int MajorAccountGroupID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GeneralAccount> GeneralAccounts { get; set; }
        public virtual MajorAccountGroup MajorAccountGroup { get; set; }
    }
}
