//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TOSS_UPGRADE.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tax
    {
        public int TaxID { get; set; }
        public string TaxDescription { get; set; }
        public string ShortDescription { get; set; }
        public string TaxPercentage { get; set; }
        public string TaxBase { get; set; }
        public int GeneralAccountID { get; set; }
        public bool isUsed { get; set; }
    
        public virtual GeneralAccount GeneralAccount { get; set; }
    }
}
